name: GitBook Deploy
  uses: docker://khs1994/gitbook
  if: github.event_name == 'push'
  with:
    args: deploy
  env:
    GIT_USERNAME: "khs1994"
    GIT_USEREMAIL: "khs1994@khs1994.com"
    GIT_BRANCH: "gh-pages"
    GITHUB_TOKEN: ${{ secrets.BOOKTOKEN }}